apiVersion: v1
kind: Service
metadata:
  name: pg-admin
  namespace: ic-webapp
  labels:
    app: pg-admin
    env: prod
spec:
  type: NodePort
  selector:
    app: pg-admin
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 80
      nodePort: 30050