apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-webapp
  namespace: ic-webapp
  labels:
    env: prod
    app: ic-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-webapp
  template:
    metadata:
      labels:
        app: ic-webapp
    spec:
      containers:
      - name: ic-webapp
        image: thierry237/ic-webapp:v1.0
        env:
        - name: ODOO_URL
          value: http://192.168.80.18:30069/
        - name: PGADMIN_URL
          value: http://192.168.80.18:30050/ 
        ports:
        - containerPort: 8080
          name: ic-webapp
