apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: ic-webapp
  labels:
    env: prod
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:10
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: toto
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
          - name: pg-data
            mountPath: /var/lib/postgresql/data
    volume:
      - name: pg-data
        hostPath:
          path: /data_k8s/postgre