apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ic-webapp
  labels:
    app: postgres
    env: prod
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP