apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-pvc
  labels:
    app: odoo
    env: prod
  namespace: ic-webapp
spec:
  storageClassName: manuel
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi