---
- name: Update System
  yum:
    name: "*"
    state: latest

- name: Install pre-requisites
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - python3
    - python3-pip
  when: ansible_distribution == "CentOS"

- name: Download pip script
  get_url:
    url: https://bootstrap.pypa.io/pip/3.6/get-pip.py
    dest: /tmp/get-pip.py

- name: Install python-pip
  command: python3 /tmp/get-pip.py
  ignore_errors: yes

- name: Install docker python
  pip:
    name: docker-py
    executable: /usr/local/bin/pip3

- name: Add Docker ce repo
  get_url:
   url: https://download.docker.com/linux/centos/docker-ce.repo
   dest: /etc/yum.repos.d/docker-ce.repo
  when: ansible_distribution == "CentOS"

- name: Install Docker on centos
  yum:
    name: docker
    state: present
  when: ansible_distribution == "CentOS"

- name: Install Docker on Amazon linux
  command: amazon-linux-extras install docker -y
  args:
    creates: /usr/bin/docker
  when: ansible-distribution == "Amazon"

- name: Add remote user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: dockerroot
    append: yes
  when: ansible-distribution == "CentOS"

- name: Add remote user to docker group on EC2
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  when: ansible-distribution == "Amazon"

- name: Start and enable the Docker daemon
  service:
    name: docker
    state: started
    enabled: yes

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/bin/docker-compose
    mode: 0755